name: "Add to Project"
description: "Set a default project board for issues to be addded to."
inputs:
  issue:
    description: "issue number, use {{ github.event.issue.number }}"
    required: true
  repository:
    description: "repository path, use {{ github.repository }}"
    required: true
  project:
    description: "project board, use the number in the slug for that board"
    required: true
  private_key:
    description: "Application Private Key"
    required: true
  app_id:
    description: "Application ID"
    required: true
  installation_id:
    description: "ID for the installation of the application"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
